/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rugved
 */
public class LasP extends javax.swing.JFrame {

    /**
     * Creates new form LasP
     */
    public LasP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Do you want to submit?");

        jButton2.setText("No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jButton1))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(82, 82, 82)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Connection conn = Connectiondb.getConnection();
       // conn = null;
       int a=0;
       String b=null;
       String str;
       int p=0;
       for(int i=1;i<10;i++)
       {
        try {
            CallableStatement stmt = null;
            //String ru = "{call projectts(?, ?)}";
            Connection c = Connectiondb.getConnection();
        Statement stmt1 = c.createStatement();
        
                 int x=0;
       String d=null;
       String str1;
       String str5;
       ResultSet rs1=null;
       try {
        Connection c1 = Connectiondb.getConnection();
        Statement s = c1.createStatement();
        str5="SELECT * FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        ResultSet rs=s.executeQuery(str5);
        while(rs.next())
        {
            x=rs.getInt(1);
        }
       }catch(Exception k){k.printStackTrace();}
       int e;
       if(x==0){e=1;}
       else{e=x;
       }
       //ps.close();
        str="SELECT * FROM Answer1 WHERE Q_ID=? and Test_ID=?";
        try{
        PreparedStatement ps;
            ps=c.prepareStatement(str);
            ps.setInt(1,i);
            ps.setInt(2,e);
        rs1=ps.executeQuery();
        while(rs1.next())
        {
            b=rs1.getString(2);
        }
        CallableStatement smt = null;
            //String ru = "{call projectts(?, ?)}";

            smt = conn.prepareCall("{call mark(?,?,?)}");
            smt.setInt(1,i);
            smt.setString(2,b);
            smt.registerOutParameter(3, java.sql.Types.INTEGER);
            smt.execute();
            a = smt.getInt(3);
            p=p+a;    }
        catch (Exception q) {
            q.printStackTrace();
        }       
       }
        catch(Exception e)
        {e.printStackTrace();}
       
       }
       String str5;
      try{ Connection con = Connectiondb.getConnection();
       Statement s = con.createStatement();
       PreparedStatement ps=null;
        
        int k=0;
        str5="SELECT Test_ID FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        
        ResultSet rs=s.executeQuery(str5);
        while(rs.next())
        {
            k=rs.getInt(1);
        }
        System.out.println(k);
         ps=con.prepareStatement("update test3 set Marks=? where Test_ID=?");
         ps.setInt(1,p);
         ps.setInt(2,k);
          rs=ps.executeQuery();
     }
      catch(Exception j)
      {j.printStackTrace();}
      JOptionPane.showMessageDialog(null,"Marks:"+p+"/11");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int b=0;
       //String d=null;
       String str1;
       String str;
       try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        str="SELECT Test_ID FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        ResultSet rs=stmt.executeQuery(str);
        while(rs.next())
        {
            b=rs.getInt(1);
        }
       }catch(Exception e){e.printStackTrace();}
       int e;
       if(b==0){e=1;}
       else{e=b;
       }
       PreparedStatement pst=null;
       PreparedStatement pst1=null;
       str1="delete from test3 where Test_ID=?";
       String str2="delete from Answer1 where Test_ID=?";
        try{
            Connection m=Connectiondb.getConnection();
            pst=m.prepareStatement(str1);
            pst1=m.prepareStatement(str2);
            pst.setInt(1,e);
            pst1.setInt(1,e);
        }
        catch(Exception q)
        {
            q.printStackTrace();
        }
        signup su=new signup();
        su.setVisible(true);
            //pst.setString(2,jPasswordField1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LasP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LasP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
