/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;
import java.sql.*;
import java.util.Enumeration;
import javax.swing.*;

/**
 *
 * @author Rugved
 */
public class QuestionP extends javax.swing.JFrame {
int y=0;
    /**
     * Creates new form QuestionP
     */
    public QuestionP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   // public void red(){
     //   jButton2.setText("fe");
    //}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int e=0;
        try{ Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        int l = 0;
        
        String d=null;
       String str1;
       String str;
        str="SELECT Q_ID FROM QA WHERE ROWNUM <=1 ORDER BY Q_ID desc";
        ResultSet rs=stmt.executeQuery(str);
        while(rs.next())
        {
            l=rs.getInt(1);
        }
       
       
       if(l==0){e=1;}
       else{e=l;
       }
    }
       catch(Exception g){g.printStackTrace();}
        if(y<e){y=y+1;
     quest(y);
     }
     else{
         LasP p=new LasP();
     p.setVisible(true);
     dispose();}
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
PreparedStatement ptstmt;
ResultSet rs=null;
    public void quest(int y)
{
    //Connection conn=new Connectiondb.getConnection();
  try{  Connection conn = Connectiondb.getConnection();
     Statement stmt = conn.createStatement();
     ptstmt=conn.prepareStatement("select Question,a,b,c,d from QA q,Options o where q.Option_ID=o.Option_ID and Q_ID=? ");
     ptstmt.setInt(1,y);
     rs=ptstmt.executeQuery();
     if(rs.next())
     {
      jLabel1.setText(rs.getString(1));
      jRadioButton1.setText(rs.getString(2));
      jRadioButton2.setText(rs.getString(3));
      jRadioButton3.setText(rs.getString(4));
      jRadioButton4.setText(rs.getString(5));
     }
     
  }
  catch(Exception e){}
}
    String text;
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        text=getSelectedButtonText(buttonGroup1);
        int b=0;
       String d=null;
       String str1;
       String str;
       try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        str="SELECT Test_ID FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        ResultSet rs=stmt.executeQuery(str);
        while(rs.next())
        {
            b=rs.getInt(1);
        }
       }catch(Exception e){e.printStackTrace();}
       int e;
       if(b==0){e=1;}
       else{e=b;
       }
       int z=0;
    System.out.println(e);
           try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        //Statement stmt2 = c.createStatement();
  
        
             stmt.executeUpdate("insert into Answer1 values('"+y+"','"+text+"','"+e+"')");
         
           }
           
catch(Exception f)
{f.printStackTrace();}
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        text=getSelectedButtonText(buttonGroup1);
          int b=0;
       String d=null;
       String str1;
       String str;
       try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        str="SELECT Test_ID FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        ResultSet rs=stmt.executeQuery(str);
        while(rs.next())
        {
            b=rs.getInt(1);
        }
       }catch(Exception e){e.printStackTrace();}
       int e;
       if(b==0){e=1;}
       else{e=b;
       }
       int z=0;
System.out.println(e);
      
try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        
         stmt.executeUpdate("insert into Answer1 values('"+y+"','"+text+"','"+e+"')");
           }
        
catch(Exception f)
{f.printStackTrace();}
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        text=getSelectedButtonText(buttonGroup1);
          int b=0;
       String d=null;
       String str1;
       String str;
       try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        str="SELECT Test_ID FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        ResultSet rs=stmt.executeQuery(str);
        while(rs.next())
        {
            b=rs.getInt(1);
        }
       }catch(Exception e){e.printStackTrace();}
       int e;
       if(b==0){e=1;}
       else{e=b;
       }
       int z=0;
    
      
try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        
         stmt.executeUpdate("insert into Answer1 values('"+y+"','"+text+"','"+e+"')");
           }
        
catch(Exception f)
{f.printStackTrace();}
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        text=getSelectedButtonText(buttonGroup1);
          int b=0;
       String d=null;
       String str1;
       String str;
       try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
        str="SELECT Test_ID FROM test3 WHERE ROWNUM <=1 ORDER BY Test_ID desc";
        ResultSet rs=stmt.executeQuery(str);
        while(rs.next())
        {
            b=rs.getInt(1);
        }
       }catch(Exception e){e.printStackTrace();}
       int e;
       if(b==0){e=1;}
       else{e=b;
       }
       int z=0;
    
      
try {
        Connection c = Connectiondb.getConnection();
        Statement stmt = c.createStatement();
          System.out.println(e);
         stmt.executeUpdate("insert into Answer1 values('"+y+"','"+text+"','"+e+"')");
           }
      
catch(Exception f)
{f.printStackTrace();}
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    
    public String getSelectedButtonText(ButtonGroup buttonGroup1) {
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
